### ISSUE TITLE
 { code: -32601, message: 'Method not found' }

### ISSUE THREAD

**Issue by Wangmmx** [PlasmNetwork/api#23]
Hi, using shiden network got error when I geting nonce from chain by `system_accountNextIndex`:
  { code: -32601, message: 'Method not found' },

And this is a common api for polkadot, 
https://polkadot.js.org/docs/substrate/rpc/#system

so I want to ask how can I reslove that? Any other JSON RPC api to get nonce?

**Comment by hoonsubin** [comment]
should be fixed with the latest updates
